# TryOS Labs

name: light_of_dawaah
description: "Illuminating Paths with Hearts Aglow"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  async: any
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.4
  google_fonts: ^6.2.1
  http: ^1.3.0
  intl: any
  quick_actions: ^1.1.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  msix: ^3.16.8
  rename: ^3.0.2

flutter:
  generate: true
  uses-material-design: true

flutter_launcher_icons:
  image_path: assets/icon/icon.png
  android: true
  min_sdk_android: 30
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: assets/icon/icon.png
  macos:
    generate: true
    image_path: assets/icon/icon.png
  ios: true
  remove_alpha_ios: true
  windows:
    generate: true
    image_path: assets/icon/icon.png
    icon_size: 192
  web:
    generate: true
    image_path: assets/icon/icon.png
    background_color: "#F0F8FF"
    theme_color: "#808080"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/icon/icon.png
  branding: assets/branding.png
  branding_mode: bottom
  color_dark: "#808080"
  image_dark: assets/icon/icon.png
  branding_dark: assets/branding.png
  android_gravity: center
  ios_content_mode: center
  web_image_mode: center
